services:
  db:
    image: postgres:15
    container_name: mediaisecho_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE__NAME}
      POSTGRES_USER: ${DATABASE__USER}
      POSTGRES_PASSWORD: ${DATABASE__PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: mediaisecho_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./infrastructure/migrations:/app/infrastructure/migrations


volumes:
  pg_data:
